"use client";

import Link from "next/link";
import { ArrowLeft, Copy, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { apiRequest, useAuth } from "../../../lib/auth";
import { BrandMark } from "../../../components/brand-mark";
type Detail = { slug:string; title:string; difficulty:"EASY"|"MEDIUM"|"HARD"; statementMd:string; constraintsMd:string; javaTemplate:string; version:number; tags:{name:string;slug:string}[]; examples:{order:number;input:string;output:string;explanation?:string}[]; favorite:boolean };
const labels={EASY:"简单",MEDIUM:"中等",HARD:"困难"};
export default function ProblemPage({ params }: { params: Promise<{ slug: string }> }) { const [slug,setSlug]=useState(""); const [problem,setProblem]=useState<Detail|null>(null); const [error,setError]=useState(""); const user=useAuth((s)=>s.user); useEffect(()=>{params.then(({slug})=>setSlug(slug));},[params]); useEffect(()=>{if(slug) apiRequest<Detail>(`/api/problems/${slug}`).then(setProblem).catch((e)=>setError(e.message));},[slug]); async function favorite(){if(!problem) return; if(!user?.id){setError("登录后可以收藏题目"); return;} try {await apiRequest(`/api/problems/${problem.slug}/favorite?enabled=${!problem.favorite}`,{method:"PUT"}); setProblem({...problem,favorite:!problem.favorite});}catch(e){setError(e instanceof Error?e.message:"收藏失败");}} if(error&&!problem)return <main className="problem-loading">{error}</main>; if(!problem)return <main className="problem-loading">正在加载题目...</main>; return <main className="detail-layout"><header className="app-topbar"><Link className="brand" href="/"><BrandMark />CodeAgent OJ</Link><nav><Link href="/">主页</Link><Link href="/problems">题库</Link></nav></header><section className="problem-pane"><Link className="breadcrumb" href="/problems"><ArrowLeft size={14}/>题库 / {problem.slug}</Link><div className="problem-title"><h1>{problem.title}</h1><button className="icon-tool" onClick={favorite} title="收藏题目"><Star size={18} fill={problem.favorite?"currentColor":"none"}/></button></div><div className="badge-row"><span className={`difficulty ${problem.difficulty.toLowerCase()}`}>{labels[problem.difficulty]}</span>{problem.tags.map(t=><span className="tag" key={t.slug}>{t.name}</span>)}</div><section className="problem-copy"><h2>题目描述</h2>{problem.statementMd.split("\n").map((line,i)=><p key={i}>{line.replaceAll("`","")}</p>)}<h2>示例</h2>{problem.examples.map(ex=><article className="sample" key={ex.order}><strong>示例 {ex.order}</strong><button className="icon-tool" onClick={()=>navigator.clipboard.writeText(ex.input)} title="复制样例"><Copy size={14}/></button><pre>输入：{ex.input}{"\n"}输出：{ex.output}</pre>{ex.explanation&&<p>{ex.explanation.replaceAll("`","")}</p>}</article>)}<h2>约束</h2>{problem.constraintsMd.split("\n").map((line,i)=><p key={i}>{line.replace("- ","")}</p>)}</section></section><section className="template-pane"><div className="editor-title"><span>Main.java</span><span>Java 21</span></div><pre className="template-code">{problem.javaTemplate}</pre><p className="template-note">运行和提交将在阶段 3 判题链路接入。</p>{error&&<p className="catalog-error">{error}</p>}</section></main>; }
