"use client";

import Link from "next/link";
import { ArrowLeft, Copy, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { apiRequest, useAuth } from "../../../lib/auth";
import { BrandMark } from "../../../components/brand-mark";
import { useLanguage } from "../../../lib/i18n";
import { useProblemsMessages } from "../../../lib/messages/problems";
type Detail = { slug:string; title:string; difficulty:"EASY"|"MEDIUM"|"HARD"; statementMd:string; constraintsMd:string; javaTemplate:string; version:number; tags:{name:string;slug:string}[]; examples:{order:number;input:string;output:string;explanation?:string}[]; favorite:boolean };
const labels={EASY:"problems.difficulty.easy",MEDIUM:"problems.difficulty.medium",HARD:"problems.difficulty.hard"} as const;
export default function ProblemPage({ params }: { params: Promise<{ slug: string }> }) { const { t } = useLanguage(); const tp = useProblemsMessages(); const [slug,setSlug]=useState(""); const [problem,setProblem]=useState<Detail|null>(null); const [error,setError]=useState(""); const user=useAuth((s)=>s.user); useEffect(()=>{params.then(({slug})=>setSlug(slug));},[params]); useEffect(()=>{if(slug) apiRequest<Detail>(`/api/problems/${slug}`).then(setProblem).catch((e)=>setError(e.message));},[slug]); async function favorite(){if(!problem) return; if(!user?.id){setError(tp("problemDetail.error.loginRequired")); return;} try {await apiRequest(`/api/problems/${problem.slug}/favorite?enabled=${!problem.favorite}`,{method:"PUT"}); setProblem({...problem,favorite:!problem.favorite});}catch(e){setError(e instanceof Error?e.message:tp("problemDetail.error.favoriteFailed"));}} if(error&&!problem)return <main className="problem-loading">{error}</main>; if(!problem)return <main className="problem-loading">{tp("problemDetail.loading")}</main>; return <main className="detail-layout"><header className="app-topbar"><Link className="brand" href="/"><BrandMark />CodeAgent OJ</Link><nav><Link href="/">{t("nav.home")}</Link><Link href="/problems">{t("nav.problems")}</Link></nav></header><section className="problem-pane"><Link className="breadcrumb" href="/problems"><ArrowLeft size={14}/>{t("nav.problems")} / {problem.slug}</Link><div className="problem-title"><h1>{problem.title}</h1><button className="icon-tool" onClick={favorite} title={tp("problemDetail.favoriteTooltip")}><Star size={18} fill={problem.favorite?"currentColor":"none"}/></button></div><div className="badge-row"><span className={`difficulty ${problem.difficulty.toLowerCase()}`}>{tp(labels[problem.difficulty])}</span>{problem.tags.map(t=><span className="tag" key={t.slug}>{t.name}</span>)}</div><section className="problem-copy"><h2>{tp("problemDetail.statement")}</h2>{problem.statementMd.split("\n").map((line,i)=><p key={i}>{line.replaceAll("`","")}</p>)}<h2>{tp("problemDetail.examples")}</h2>{problem.examples.map(ex=><article className="sample" key={ex.order}><strong>{tp("problemDetail.example")} {ex.order}</strong><button className="icon-tool" onClick={()=>navigator.clipboard.writeText(ex.input)} title={tp("problemDetail.copyTooltip")}><Copy size={14}/></button><pre>{tp("problemDetail.inputLabel")}{ex.input}{"\n"}{tp("problemDetail.outputLabel")}{ex.output}</pre>{ex.explanation&&<p>{ex.explanation.replaceAll("`","")}</p>}</article>)}<h2>{tp("problemDetail.constraints")}</h2>{problem.constraintsMd.split("\n").map((line,i)=><p key={i}>{line.replace("- ","")}</p>)}</section></section><section className="template-pane"><div className="editor-title"><span>Main.java</span><span>Java 21</span></div><pre className="template-code">{problem.javaTemplate}</pre><p className="template-note">{tp("problemDetail.templateNote")}</p>{error&&<p className="catalog-error">{error}</p>}</section></main>; }
