"use client";

import Link from "next/link";
import { Camera, Check, ChevronLeft, CircleAlert, LogOut, Save, UserRound } from "lucide-react";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { apiRequest, authRequest, useAuth } from "../../lib/auth";
import styles from "./profile.module.css";

type Submission = { problemTitle:string; status:string; createdAt:string };
type Profile = { id:string;username:string;email:string;displayName:string;avatarUrl?:string;avatarColor:"orange"|"green"|"blue"|"red";createdAt:string;solvedCount:number;totalSubmissions:number;acceptedSubmissions:number;recentSubmissions:Submission[] };
const colors: Profile["avatarColor"][] = ["orange","green","blue","red"];
const colorNames = {orange:"橙色",green:"绿色",blue:"蓝色",red:"红色"};
function initial(name:string){return Array.from(name.trim())[0]?.toUpperCase() || "U";}

export default function ProfilePage(){const session=useAuth();const [profile,setProfile]=useState<Profile|null>(null);const [name,setName]=useState("");const [color,setColor]=useState<Profile["avatarColor"]>("orange");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);const base=process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";
  useEffect(()=>{if(!session.accessToken){setError("请先登录后查看个人资料。");return;}apiRequest<Profile>("/api/profile").then((data)=>{setProfile(data);setName(data.displayName);setColor(data.avatarColor);}).catch((cause)=>setError(cause instanceof Error?cause.message:"资料读取失败"));},[session.accessToken]);
  async function save(){if(!name.trim())return setError("昵称不能为空");setBusy(true);setError("");try{const data=await apiRequest<Profile>("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:name,avatarColor:color})});setProfile(data);session.setSession({...session,user:{...session.user,displayName:data.displayName}});setNotice("资料已保存");}catch(cause){setError(cause instanceof Error?cause.message:"保存失败");}finally{setBusy(false);}}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setError("头像文件不能超过 2MB");return;}const form=new FormData();form.append("file",file);setBusy(true);setError("");try{const response=await fetch(`${base}/api/profile/avatar`,{method:"PUT",headers:{Authorization:`Bearer ${session.accessToken}`},body:form});const body=await response.json();if(!response.ok)throw new Error(body.detail??"头像上传失败");setProfile(body.data);setNotice("头像已更新");}catch(cause){setError(cause instanceof Error?cause.message:"头像上传失败");}finally{setBusy(false);event.target.value="";}}
  async function logout(){try{if(session.refreshToken)await authRequest<void>("/api/auth/logout",{refreshToken:session.refreshToken});}finally{session.clearSession();window.location.assign("/login");}}
  if(!profile)return <main className={styles.loading}>{error?<><CircleAlert size={20}/><p>{error}</p><Link href="/login">前往登录</Link></>:<p>正在载入个人资料...</p>}</main>;
  const rate=profile.totalSubmissions?Math.round(profile.acceptedSubmissions/profile.totalSubmissions*100):0;
  return <main className={styles.shell}><header><Link href="/" className={styles.back}><ChevronLeft size={16}/>返回概览</Link><button onClick={logout} className={styles.logout}><LogOut size={15}/>退出登录</button></header><section className={styles.hero}><div className={`${styles.avatar} ${styles[color]}`}>{profile.avatarUrl?<img src={`${base}${profile.avatarUrl}`} alt={`${profile.displayName} 的头像`}/>:initial(profile.displayName)}<button onClick={()=>input.current?.click()} aria-label="上传头像" title="上传头像"><Camera size={16}/></button><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></div><div><p className={styles.kicker}>个人资料</p><h1>{profile.displayName}</h1><p>@{profile.username} · 注册于 {new Date(profile.createdAt).toLocaleDateString("zh-CN")}</p></div></section><section className={styles.content}><article className={styles.edit}><div className={styles.sectionTitle}><div><p className={styles.kicker}>身份设置</p><h2>你的个人信息</h2></div><UserRound size={18}/></div><label>昵称<input value={name} maxLength={64} onChange={(event)=>setName(event.target.value)} /></label><p className={styles.hint}>昵称会显示在首页侧栏和个人中心。</p><label>邮箱<input value={profile.email} disabled /></label><p className={styles.hint}>邮箱暂不支持在线修改。</p><div className={styles.colorRow}><span>默认头像颜色</span>{colors.map((item)=><button key={item} className={`${styles.swatch} ${styles[item]} ${color===item?styles.selected:""}`} onClick={()=>setColor(item)} aria-label={colorNames[item]} title={colorNames[item]}/>)}</div><p className={styles.hint}>支持 PNG、JPG、WebP，最大 2MB。上传后将优先显示图片头像。</p>{error&&<p className={styles.error}><CircleAlert size={15}/>{error}</p>}{notice&&<p className={styles.notice}><Check size={15}/>{notice}</p>}<button className={styles.save} disabled={busy} onClick={save}><Save size={15}/>{busy?"保存中":"保存资料"}</button></article><aside className={styles.stats}><p className={styles.kicker}>练习概览</p><div className={styles.stat}><strong>{profile.solvedCount}</strong><span>已解决题目</span></div><div className={styles.stat}><strong>{rate}%</strong><span>提交通过率</span></div><div className={styles.stat}><strong>{profile.totalSubmissions}</strong><span>累计提交</span></div></aside><article className={styles.recent}><div className={styles.sectionTitle}><div><p className={styles.kicker}>最近提交</p><h2>判题记录</h2></div><Link href="/problems">继续做题</Link></div>{profile.recentSubmissions.length?profile.recentSubmissions.map((item,index)=><div className={styles.submission} key={`${item.createdAt}-${index}`}><span>{item.problemTitle}</span><b className={item.status==="AC"?styles.accepted:styles.failed}>{item.status}</b><time>{new Date(item.createdAt).toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time></div>):<p className={styles.empty}>还没有提交记录。</p>}</article></section></main>;
}
